name: Package and release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -p 1196143
